
T = {}
env = {}

--[[ TTS Load function. TODO: may not even need script any more.  Keeping as placeholder until confirmed. --]]
function onLoad(saved_state)
  Wait.frames(function()
    env.trace = Global.getTable("env").trace
    T.name = Global.getTable("C").regions_template[self.getGUID()].name
    if env.trace then log("Region "..T.name.." loaded") end
  end, 1)
end

-- #include ~/github/tts-lib/Utils.ttslua
